### ISSUE TITLE
How the database can be changed from HSQLDB to MySQL DB

### ISSUE THREAD

**Issue by RaviTeja457** [d-rep/URL-Shortener#1]
How can we change the database from HSQL db to mysql..?Could you please guide

**Comment by d-rep** [comment]
No code changes are necessary, and out-of-the-box this webapp will run on MySQL.

First, build the project with Maven and deploy the WAR file to an app server like Tomcat.  You'll simply need a JNDI entry `jdbc/url_test` setup with URL/username/password to your MySQL database.

**Comment by RaviTeja457** [comment]
I have done and achieved thank you a lot sir
